### ISSUE TITLE
No responding mc!help #command

### ISSUE THREAD

**Issue by FlorianMrtnz** [eduardozgz/member-counter-bot#1]
All in title :c
eg when we do mc!help setdigit nothing happens

**Comment by eduardozgz** [comment]
Fixed in [d013c57](https://github.com/eduardozgz/member-counter-bot/commit/d013c576a445ea023aaa559c6d3cd7a12b46ca5c#diff-815eb738cf1bd5bb8e91c9bd36dc360dR14)

**Comment by eduardozgz** [comment]
Fixed in [d013c57](https://github.com/eduardozgz/member-counter-bot/commit/d013c576a445ea023aaa559c6d3cd7a12b46ca5c#diff-815eb738cf1bd5bb8e91c9bd36dc360dR14)
