### ISSUE TITLE
[SUGGESTION]: 24 hour time option

### ISSUE THREAD

**Issue by Fire0x** [eduardozgz/member-counter-bot#112]
**Is your feature request related to a problem? Please describe.**
For cloak have the option to switch from 12 hour time to 24 hour time or to allow to pick between 12 / 24 hour depending on the cloak count.

**Describe the solution you'd like**
The ability to have 24 hour time and to possibly have the option to toggle it for individual cloak count.

**Describe alternatives you've considered**
To just stick to 12 hour time. (I personally don't use 12 hour time).

**Additional context**
24 hour - 00:00 
12 Hour - 12:00 am
24 hour - 23:24 
12 hour - 11:24pm

**Comment by eduardozgz** [comment]
You can do this by:
- Changing the server locale in the bot config
   - This will affect all the counters
   - Example: `mc!locale uk`

- Adding custom setttings inside the counter
   - This will affect only one counter 
   - Example: `{eyJsb2NhbGUiOiJ1ayJ9:clock:Europe/Madrid}`
   - You can use [this website](https://member-counter.eduardozgz.com/utils/overwrite-settings) to setup this easily, the locale you are looking for is probably `uk`
   - Or manually by following [these steps](https://github.com/eduardozgz/member-counter-bot/issues/98)

If you need more help you can get support here: https://discord.com/invite/g4MfV6N
