### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by AshVincent** [eduardozgz/member-counter-bot#203]
**Describe the bug**

- Not sure if it's a bug or I skipped a step, the bot would not respond to commands.

**To Reproduce**
Steps to reproduce the behaviour:

1. Add to server
2. mc!help (Doesn't work)
3. Went to this page.
4. mc!setup (Doesn't work)
5. mc!prefix (Doesn't work)
6. mc!prefix setup (Doesn't work)
7. mc!prefix prefix (Doesn't work)
8. Made an account in github to report the issue (I don't know anything about this stuff so maybe I needed to give some permissions to the bot or something?)

**Expected behaviour**

- I expected it to start working as the other bots when I start making commands.

**Screenshots**

![Screenshot (2293)](https://user-images.githubusercontent.com/82382040/114389268-ff0bff80-9bbe-11eb-8ba3-ff0248637404.png)

**Additional context**

- Nothing.

**Comment by eduardozgz** [comment]
@AshVincent Please, join the support server -> https://discord.com/invite/g4MfV6N
