### ISSUE TITLE
[SUGGESTION]: Make delete all data button harder to use

### ISSUE THREAD

**Issue by eyal282** [eduardozgz/member-counter-bot#204]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [I have to conatantly think where my cursor is]

**Describe the solution you'd like**
To delete all of your data, you have to do both:
1. React to the check emoji
2. Add 9 distinct reactions to the message, any reaction is possible

**Describe alternatives you've considered**
Installing skype.

**Additional context**

**Comment by eduardozgz** [comment]
Don't install skype, get [guilded](https://www.guilded.gg/)

**Comment by eduardozgz** [comment]
Also, having to add 9 emojis looks like a pain, instead of reacting emojis, I would ask the user to send an exact text, like: 
"Please, send exactly this text if you wanna delete all your data: 'I want to delete all my data'"

**Comment by eyal282** [comment]
> Also, having to add 9 emojis looks like a pain, instead of reacting emojis, I would ask the user to send an exact text, like:
> "Please, send exactly this text if you wanna delete all your data: 'I want to delete all my data'"

I absolutely can settle with this. Can you do it?

**Comment by phoebe-leong** [comment]
why cant it just be easy??

**Comment by phoebe-leong** [comment]
to use the delete data button

**Comment by eduardozgz** [comment]
@phoebe-leong Because I already seen like 3 or 4 people delete his data accidentally in my own server, bacause they didn't read at all the confirmation message

**Comment by phoebe-leong** [comment]
ohh right ok
