### ISSUE TITLE
[BUG]: {escape} tag and comma bug

### ISSUE THREAD

**Issue by SeaSon2002** [eduardozgz/member-counter-bot#283]
**Describe the bug**
weird behavior with new {escape:} tag, it adds a "/". All content after the first comma inside a tag doesnt show up

**To Reproduce**

1. Create a {countdown} counter -editchannel 123456789 {countdown:1640970000:%d day, %h hour, %m min}
2. category name is updated with its name not fully displayed (pic1)
3. tried using command -editchannel 123456789 {countdown:1640970000:%d day{escape:,} %h hour {escape:,} %m min} results in the name of the category having 3 extra "/" ( pic2)

**Expected behavior**
things should work like the public stable bot. I can use the countdown counter normally without adding {escape} or '/' before a comma.

**Screenshots**
pic1
![image](https://user-images.githubusercontent.com/61407079/135415879-8ad1bab2-bc2c-4281-a667-d170421eec55.png)
pic2
![image](https://user-images.githubusercontent.com/61407079/135415937-f48a60c3-0a25-4bab-9878-b0156bf986e5.png)

**Comment by eduardozgz** [comment]
Nice catch! Looks like I forgot to remove the escape characters when parsing the args
