### ISSUE TITLE
[SUGGESTION]: Counters in categories

### ISSUE THREAD

**Issue by Eldrimo** [eduardozgz/member-counter-bot#294]
**Is your feature request related to a problem? Please describe.**
Not rlly

**Describe the solution you'd like**
MAKE CATEGORY COUTNERS AN OPTION as that will be epic :D 

**Describe alternatives you've considered**
 Just copy serverstats, as they only thing they have on you is category

**Additional context**
 My username is **Eldrimo#9999** if this gets added so u know who to send badge to :p

**Comment by eduardozgz** [comment]
Closing this because this is already a thing :P
